# Generated by Django 6.0.3 on 2026-03-23 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('vk', 'VK')], max_length=20, verbose_name='Канал')),
                ('notification_type', models.CharField(choices=[('created', 'Создание записи'), ('reminder_3h', 'Напоминание за 3 часа'), ('confirmed', 'Подтверждение записи'), ('cancelled', 'Отмена записи')], max_length=30, verbose_name='Тип уведомления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('external_message_id', models.CharField(blank=True, max_length=255, verbose_name='Внешний ID сообщения')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('error_text', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='appointments.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-created_at'],
            },
        ),
    ]
