# Generated by Django 6.0.3 on 2026-04-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('max', 'Max')], max_length=20, verbose_name='Канал'),
        ),
    ]
