# Generated by Django 6.0.3 on 2026-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_notifications', '0002_alter_notificationlog_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPrelink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен привязки Telegram')),
                ('chat_id', models.CharField(blank=True, max_length=50, verbose_name='Telegram chat id')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Привязан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Временная привязка Telegram',
                'verbose_name_plural': 'Временные привязки Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
