# Generated by Django 6.0.3 on 2026-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_notifications', '0003_telegramprelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKPrelink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен привязки VK')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='VK user id')),
                ('peer_id', models.CharField(blank=True, max_length=50, verbose_name='VK peer id')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Привязан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Временная привязка VK',
                'verbose_name_plural': 'Временные привязки VK',
                'ordering': ['-created_at'],
            },
        ),
    ]
