# Generated by Django 6.0.3 on 2026-04-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_doctor_contact_requested_at_and_more'),
        ('doctor_notifications', '0004_vkprelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKDialogState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='VK user id')),
                ('peer_id', models.CharField(blank=True, max_length=50, verbose_name='VK peer id')),
                ('state', models.CharField(choices=[('idle', 'Ожидание'), ('has_active_appointment', 'Есть активная запись'), ('confirm_cancel', 'Подтверждение отмены')], default='idle', max_length=50, verbose_name='Состояние')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vk_dialog_states', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Состояние VK-диалога',
                'verbose_name_plural': 'Состояния VK-диалогов',
                'ordering': ['-updated_at'],
            },
        ),
    ]
