# Generated by Django 6.0.3 on 2026-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_notifications', '0005_vkdialogstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkdialogstate',
            name='last_action_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее действие'),
        ),
        migrations.AddField(
            model_name='vkdialogstate',
            name='last_menu_kind',
            field=models.CharField(choices=[('none', 'Нет меню'), ('booking', 'Меню записи'), ('active_appointment', 'Меню активной записи'), ('cancel_confirm', 'Меню подтверждения отмены')], default='none', max_length=50, verbose_name='Последнее меню'),
        ),
        migrations.AddField(
            model_name='vkdialogstate',
            name='last_menu_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее меню отправлено'),
        ),
        migrations.AddField(
            model_name='vkdialogstate',
            name='last_processed_event_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Последний обработанный event_id'),
        ),
    ]
