# Generated by Django 6.0.3 on 2026-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_notifications', '0006_vkdialogstate_last_action_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkdialogstate',
            name='last_menu_kind',
            field=models.CharField(choices=[('none', 'Нет меню'), ('booking', 'Меню записи'), ('active_root', 'Корневое меню активной записи'), ('manage', 'Меню управления записью'), ('cancel_confirm', 'Меню подтверждения отмены')], default='none', max_length=50, verbose_name='Последнее меню'),
        ),
    ]
