# Generated by Django 6.0.3 on 2026-09-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_notifications', '0007_alter_vkdialogstate_last_menu_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramPrelink',
        ),
    ]
