# Generated by Django 6.0.3 on 2026-03-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('scheduling', '0002_alter_availabilityrule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись пациента', 'verbose_name_plural': 'Записи пациентов'},
        ),
        migrations.AlterModelOptions(
            name='appointmentattachment',
            options={'verbose_name': 'Файл пациента', 'verbose_name_plural': 'Файлы пациента'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='legal_consent_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Версия согласия'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='legal_offer_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Версия оферты'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='legal_privacy_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Версия политики'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consent_given',
            field=models.BooleanField(verbose_name='Согласие на обработку данных'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя пациента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='offer_accepted',
            field=models.BooleanField(verbose_name='Оферта принята'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='privacy_accepted',
            field=models.BooleanField(verbose_name='Политика конфиденциальности принята'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина обращения'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='scheduling.timeslot', verbose_name='Слот времени'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appointmentattachment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='appointments.appointment', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='appointmentattachment',
            name='file',
            field=models.FileField(upload_to='appointments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='appointmentattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружен'),
        ),
    ]
