# Generated by Django 6.0.3 on 2026-04-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='max_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Max контакт'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username'),
        ),
    ]
