# Generated by Django 6.0.3 on 2026-04-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_max_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram chat id'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram link token'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telegram привязан'),
        ),
    ]
