# Generated by Django 6.0.3 on 2026-04-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('max', 'Max')], max_length=20, verbose_name='Предпочтительный способ связи'),
        ),
    ]
