# Generated by Django 6.0.3 on 2026-04-09 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_preferred_contact_method'),
        ('scheduling', '0003_alter_availabilityrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='scheduling.timeslot', verbose_name='Слот времени'),
        ),
    ]
