# Generated by Django 6.0.3 on 2026-04-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_slot'),
        ('scheduling', '0003_alter_availabilityrule_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'confirmed'])), fields=('slot',), name='unique_active_appointment_per_slot'),
        ),
    ]
