# Generated by Django 6.0.3 on 2026-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_unique_active_appointment_per_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vk_link_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='VK link token'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vk_linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VK привязан'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vk_peer_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='VK peer id'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vk_user_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='VK user id'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('vk', 'VK')], max_length=20, verbose_name='Предпочтительный способ связи'),
        ),
    ]
