# Generated by Django 6.0.3 on 2026-04-15 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_vk_link_token_appointment_vk_linked_at_and_more'),
        ('scheduling', '0003_alter_availabilityrule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='max_contact',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.timeslot', verbose_name='Слот времени'),
        ),
    ]
