# Generated by Django 6.0.3 on 2026-04-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_remove_appointment_max_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_contact_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запрос связи с врачом'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_response',
            field=models.CharField(blank=True, choices=[('', 'Нет ответа'), ('yes', 'Смогу'), ('no', 'Не смогу'), ('doctor_contact', 'Связь с врачом')], default='', max_length=30, verbose_name='Ответ на напоминание'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ответ на напоминание получен'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание отправлено'),
        ),
    ]
