# Generated by Django 6.0.3 on 2026-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_doctor_contact_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Telegram chat id'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='telegram_link_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Telegram link token'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vk_link_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='VK link token'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vk_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='VK user id'),
        ),
    ]
