# Generated by Django 6.0.3 on 2026-09-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_add_indexes_to_token_and_id_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='telegram_link_token',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='telegram_linked_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='telegram_username',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('vk', 'VK')], max_length=20, verbose_name='Предпочтительный способ связи'),
        ),
    ]
