# Generated by Django 6.0.3 on 2026-03-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'verbose_name': 'Юридический документ', 'verbose_name_plural': 'Юридические документы'},
        ),
        migrations.AlterModelOptions(
            name='siteblock',
            options={'verbose_name': 'Блок сайта', 'verbose_name_plural': 'Блоки сайта'},
        ),
    ]
