# Generated by Django 6.0.3 on 2026-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('vk_user_id', models.CharField(max_length=100, unique=True, verbose_name='VK User ID')),
                ('vk_first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя VK')),
                ('vk_last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия VK')),
                ('vk_avatar_url', models.URLField(blank=True, verbose_name='Аватар VK')),
                ('can_receive_community_messages', models.BooleanField(default=False, verbose_name='Разрешены сообщения от сообщества')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Связка VK аккаунта',
                'verbose_name_plural': 'Связки VK аккаунтов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VKIncomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Тип события')),
                ('event_id', models.CharField(blank=True, max_length=255, verbose_name='ID события')),
                ('object_data', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Входящее событие VK',
                'verbose_name_plural': 'Входящие события VK',
                'ordering': ['-created_at'],
            },
        ),
    ]
