# Generated by Django 6.0.3 on 2026-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж')),
                ('prodoktorov_url', models.URLField(blank=True, verbose_name='Ссылка на ПроДокторов')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес приема')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
