# Generated by Django 6.0.3 on 2026-03-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Профиль врача', 'verbose_name_plural': 'Профили врача'},
        ),
    ]
