# Generated by Django 6.0.3 on 2026-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='header_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/header/', verbose_name='Аватар для шапки'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/', verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
