# Generated by Django 6.0.3 on 2026-03-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_header_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='dzen_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Дзен'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='vk_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на VK'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='yandex_maps_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Яндекс.Карты'),
        ),
    ]
