# Generated by Django 6.0.3 on 2026-03-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorprofile_dzen_url_doctorprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='yandex_maps_url',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='yandex_maps_embed_url',
            field=models.URLField(blank=True, help_text='Сюда вставляется именно embed/iframe ссылка для отображения карты на сайте.', verbose_name='Ссылка для встроенной Яндекс.Карты'),
        ),
    ]
