# Generated by Django 6.0.3 on 2026-04-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctorprofile_yandex_maps_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='vk_url',
        ),
    ]
