# Generated by Django 6.0.3 on 2026-04-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctorprofile_vk_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='vk_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на VK'),
        ),
    ]
