# Generated by Django 6.0.3 on 2026-03-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityrule',
            options={'verbose_name': 'Правило расписания', 'verbose_name_plural': 'Правила расписания'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Слот времени', 'verbose_name_plural': 'Слоты времени'},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
    ]
